accounts/urls.py
from django.http import HttpResponseRedirect
from django.urls import path
from accounts.views import *

app_name = 'accounts'


urlpatterns = [
    path('mac/', BlankView.as_view(), name='blank'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<str:student_number>/', UserDetailsView.as_view(), name='user_details'),
    path('<str:student_number>/edit', UserUpdateView.as_view(), name='user_update'),
]

dcan/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include, reverse
from django.conf.urls.static import static

from dcan import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: HttpResponseRedirect(reverse("accounts:blank"))),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('course/', include(('courses.urls', 'courses'), namespace='courses')),
    path('questionaire/', include(('qa.urls', 'qa'), namespace='qa')),
    path('backrooms/', include('chatroom.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .views import *


urlpatterns = [

    path('question/create/', QuestionCreateView.as_view(), name='create_quest'),
    path('questions/', QuestionAllView.as_view(), name='all_questions'),
    path('myquestions/', MyQuestionAllView.as_view(), name='my_questions'),
    path('question/<int:question_id>/', QuestionDetailView.as_view(), name='detailed_question'),
    path('question/<int:question_id>/vote/', QuestionVoteView.as_view(), name='question_vote'),
    path('question/<int:question_id>/<int:comment_id>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path("question/<int:question_id>/delete/", QuestionDeleteView.as_view(), name="delete_question"),
    path('json_pull_request/', QuestionNamesViaJson.as_view(), name='json_pull_request'),
    path('question/<int:question_id>/question_status/', QuestionStatusTogglerView.as_view(), name='question_status'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class CustomUser(AbstractUser):

    WHO = ((1, "STUDENT"),
           (2, "INSTRUCTOR")
           )
#integer choices
    NUMBERS = ((1, "1st"),
               (2, "2nd"),
               (3, "3rd"),
               (4, "4th"),
               (5, "5th"),
               (6, "6th"),
               (7, "7th"),
               (8, "8th"),
               (9, "9th"),
               )

    SUBJECT_CHOICES = (
        ("CENG", "Computer Science"),
        ("ENG", "Engineering"),
        ("BIO", "Biology"),
    )

    student_number = models.CharField(unique=True, blank=True, null=True)
    status = models.IntegerField(choices=WHO, default=1)

    # is_student = models.BooleanField(default=True)

    year_of_student = models.IntegerField(choices=NUMBERS, default=1, null=True, blank=True)

    # daha sonra ilk kayıt olduğu anda yılını belirttiği
    # vakit normal zaman diliminden semestrı belirtilebilir

#null kaldır!!!

    semester_of_student = models.IntegerField(default=1, null=True, blank=True)
    """"
    For some reason doesn't work!
     semester = ForeignKey("Semester", null=True, blank=True,
    related_name="enrolled_students", on_delete=models.CASCADE)
    """
    study = models.CharField(choices=SUBJECT_CHOICES, max_length=50, null=True, blank=True)

    def __str__(self):
        return self.get_full_name()


""" 
According to status value courses = taker or giver

An abstract base class implementing a fully featured User model with
admin-compliant permissions.

Username and password are required. Other fields are optional.
username
first_name
last_name
email
"""

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth.forms import UserChangeForm


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }))


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'student_number', 'year_of_student',
                  'semester_of_student', 'study')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'First Name',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Last Name',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
    }))
    student_number = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Student Number',
    }))
    year_of_student = forms.ChoiceField(choices=CustomUser.NUMBERS, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    semester_of_student = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Semester',
    }))
    study = forms.ChoiceField(choices=CustomUser.SUBJECT_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm Password',
    }))


class CustomUserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'student_number', 'year_of_student',
                  'semester_of_student', 'study')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'First Name',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Last Name',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
    }))
    student_number = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Student Number',
    }))
    year_of_student = forms.ChoiceField(choices=CustomUser.NUMBERS, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    semester_of_student = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Semester',
    }))
    study = forms.ChoiceField(choices=CustomUser.SUBJECT_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
    }))

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from .forms import *
from .models import CustomUser

# Create your views here.

# can be made into app !?


class BlankView(LoginRequiredMixin, View):
    template_name = 'accounts/blank.html'
    login_url = 'accounts:login'

    def get(self, request):

        context = {
            'section_links': [
                {'name': 'Profile',
                 'url': reverse('accounts:user_details', kwargs={'student_number': request.user.student_number})},
                {'name': 'My Curriculum',
                 'url': reverse('courses:courses_curriculum', kwargs={'program_code': request.user.study})},
                {'name': 'QBank',
                 'url': reverse('qa:all_questions')},
                {'name': 'Dexter',
                 'url': reverse('courses:dexter')},
                {'name': 'Backrooms',
                 'url': reverse('chatroom:index')},
            ]
        }
        return render(request, self.template_name, context)


class LoginView(View):
    form_class = CustomLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():

            # form.cleaned_data returns a dictionary of validated form input fields and their values,
            # where string primary keys are returned as objects.
            # or so they say

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('accounts:blank'))
        return render(request, self.template_name, {'form': form})


class SignUpView(View):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # logger
            return redirect(reverse('accounts:blank'))
        return render(request, self.template_name, {'form': form})


class UserDetailsView(LoginRequiredMixin, View):
    template_name = 'accounts/user_details.html'
    login_url = 'accounts:login'

    def get(self, request, student_number):
        if request.user.student_number == student_number:
            user = get_object_or_404(CustomUser, student_number=student_number)
            return render(request, self.template_name, {'user': user})
        else:
            return redirect(reverse('accounts:login'))


class UserUpdateView(LoginRequiredMixin, View):
    form_class = CustomUserUpdateForm
    template_name = 'accounts/user_update.html'
    login_url = 'accounts:login'

    def get(self, request, student_number):
        if request.user.student_number == student_number:
            user = get_object_or_404(CustomUser, student_number=student_number)
            form = self.form_class(instance=user)
            return render(request, self.template_name, {'form': form, 'user': user})
        else:
            return redirect(reverse('accounts:login'))

    def post(self, request, student_number):
        if request.user.student_number == student_number:
            user = get_object_or_404(CustomUser, student_number=student_number)
            form = self.form_class(request.POST, instance=user)
            if form.is_valid():
                form.save()
                return redirect(reverse('accounts:blank'))
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('accounts:login')


class LogoutView(LoginRequiredMixin, View):
    login_url = 'accounts:login'

    def post(self, request):
        logout(request)
        return redirect(reverse('accounts:login'))

accounts/templates/accounts/blank.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAC</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />

    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            margin: 100px;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
        }

        .window {
            border: 2px solid #000;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 8px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .title-bar-text {
            font-size: 1.4rem;
        }

        .title-bar-controls button {
            width: 15px;
            height: 15px;
            border: none;
            background-color: #fff;
        }

        .window-body {
            padding: 20px;
            background-color: #f0f0f0;
            border-top: 2px solid #000;
        }

        ul.list-group {
            list-style-type: none;
            padding: 0;
        }

        .list-group-item {
            background-color: #fff;
            border: 2px solid #000;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 4px;
        }

        .list-group-item a {
            text-decoration: none;
            color: #00008B;
            font-weight: bold;
            font-size: 1.1rem;
        }

        .list-group-item a:hover {
            color: darkblue;
        }
    </style>

</head>
<body>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">Main Access Channel</div>
            <div class="title-bar-controls">
                <button aria-label="Minimize"></button>
                <button aria-label="Maximize"></button>
                <button aria-label="Close" onclick="logout()"></button>
                <script>
                    function logout() {

                        if(confirm("Do you wish to log-out?")) {
                            let form = document.createElement('form');
                            form.method = 'POST';
                            form.action = "{% url 'accounts:logout' %}";
                            let csrfToken = document.createElement('input');
                            csrfToken.type = 'hidden';
                            csrfToken.name = 'csrfmiddlewaretoken';
                            csrfToken.value = '{{ csrf_token }}'; // Pass the CSRF token from Django context!?!?
                            form.appendChild(csrfToken);
                            document.body.appendChild(form);
                            form.submit();
                        }

                    }
                </script>

            </div>
        </div>
        <div class="window-body">
            <ul class="list-group">
                {% for link in section_links %}
                <li class="list-group-item">
                    <a href="{{ link.url }}">{{ link.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />

    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            max-width: 400px;
            width: 100%;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 12px 16px;
            font-size: 1.5rem;
            text-align: center;
        }

        .window-body {
            padding: 20px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            font-weight: bold;
            font-size: 1.1rem;
            color: #00008B;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 2px solid #00008B;
            border-radius: 4px;
            font-size: 1rem;
        }

        .text-danger {
            color: red;
            font-size: 0.9rem;
            margin-top: 5px;
        }

        .btn-primary {
            display: block;
            width: 100%;
            background-color: #00008B;
            color: #fff;
            border: none;
            padding: 12px;
            border-radius: 4px;
            font-size: 1.1rem;
            cursor: pointer;
            margin-top: 10px;
        }

        .btn-primary:hover {
            background-color: #003580;
        }

        .text-center {
            text-align: center;
        }

        .btn-link {
            color: #00008B;
            font-weight: bold;
            text-decoration: none;
        }

        .btn-link:hover {
            text-decoration: underline;
        }

        p {
            font-size: 1rem;
            color: #00008B;
        }
    </style>
</head>
<body>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">Sign In</div>
        </div>
        <div class="window-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="text-danger">
                            {{ form.username.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                    {% if form.password.errors %}
                        <div class="text-danger">
                            {{ form.password.errors }}
                        </div>
                    {% endif %}
                </div>
                {% if form.non_field_errors %}
                    <div class="text-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <button type="submit" class="btn-primary">Sign In</button>
            </form>
            <div class="text-center mt-3">
                <p>Don't have an account? <a href="{% url 'accounts:signup' %}" class="btn-link">Sign Up</a></p>
            </div>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />

    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 100px;
        }

        .container {
            max-width: 500px;
            width: 100%;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 12px 16px;
            font-size: 1.5rem;
            text-align: center;
        }

        .window-body {
            padding: 20px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            font-weight: bold;
            font-size: 1.1rem;
            color: #00008B;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 2px solid #00008B;
            border-radius: 4px;
            font-size: 1rem;
        }

        .text-danger {
            color: red;
            font-size: 0.9rem;
            margin-top: 5px;
        }

        .alert {
            background-color: #f8d7da;
            color: #721c24;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 4px;
            border: 1px solid #f5c6cb;
        }

        .btn-primary {
            display: block;
            width: 100%;
            background-color: #00008B;
            color: #fff;
            border: none;
            padding: 12px;
            border-radius: 4px;
            font-size: 1.1rem;
            cursor: pointer;
            margin-top: 10px;
            text-align: center;
        }

        .btn-primary:hover {
            background-color: #003580;
        }

        .btn-secondary {
            display: block;
            width: 100%;
            background-color: #6c757d;
            color: #fff;
            border: none;
            padding: 12px;
            border-radius: 4px;
            font-size: 1.1rem;
            cursor: pointer;
            margin-top: 10px;
            text-align: center;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
        }

        .button-group {
            margin-top: 20px;
        }

    </style>
</head>
<body>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">Sign Up</div>
        </div>
        <div class="window-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert">
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="text-danger">
                                {% for error in field.errors %}
                                    <small>{{ error }}</small>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-group">
                    <button type="submit" class="btn-primary">Create Account</button>
                    <a href="{% url 'accounts:blank' %}" class="btn-secondary">Back to MAC</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/user_details.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Details</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />
    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            padding: 20px;
            margin: 100px;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
        }

        .card {
            padding: 10px;
            background-color: #fff;
            border: 2px solid #000;
            border-radius: 4px;
        }

        .card-header {
            background-color: #f0f0f0;
            padding: 10px;
            border-bottom: 2px solid #000;
        }

        .card-title {
            margin: 0;
            font-size: 1.4rem;
        }

        .card-body {
            padding: 10px;
        }

        .card-body p {
            font-size: 1rem;
            margin-bottom: 8px;
        }

        .card-footer {
            padding: 10px;
            border-top: 2px solid #000;
            background-color: #f0f0f0;
            display: flex;
            justify-content: space-between;
        }

        .btn-primary {
            color: white;
            background-color: #00008B;
            padding: 5px 10px;
            border-radius: 4px;
            text-decoration: none;
            border: 2px solid #000;
            font-size: 0.9rem;
        }

        .btn-secondary {
            color: #000;
            background-color: #d3d3d3;
            padding: 5px 10px;
            border-radius: 4px;
            text-decoration: none;
            border: 2px solid #000;
            font-size: 0.9rem;
        }

        #delete-button {
            background-color: red;
            color: white;
            padding: 5px 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 0.9rem;
        }

        #delete-button:hover {
            background-color: darkred;
        }
    </style>
</head>
<body>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">User Details</div>
        </div>
        <div class="window-body">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{ user.get_full_name }}</h4>
                </div>
                <div class="card-body">
                    <p><strong>Username:</strong> {{ user.username }}</p>
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>Student Number:</strong> {{ user.student_number }}</p>
                    <p><strong>Status:</strong> {{ user.get_status_display }}</p>
                    <p><strong>Year:</strong> {{ user.get_year_of_student_display }}</p>
                    <p><strong>Semester:</strong> {{ user.semester_of_student }}</p>
                    <p><strong>Study:</strong> {{ user.get_study_display }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'accounts:user_update' user.student_number %}" class="btn-primary">Edit Details</a>
                    <a href="{% url 'accounts:blank' %}" class="btn-secondary">Back to MAC</a>
                    <!-- Add the delete button -->
                    <button id="delete-button" class="btn-secondary" data-user-id="{{ user.id }}">Delete Account</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/user_update.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />
    <style>
        body {
            background-color: #c0c0c0;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
        }

        .window {
            border: 2px solid #000;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 8px;
        }

        .title-bar-text {
            font-size: 1.4rem;
        }

        .window-body {
            padding: 20px;
            background-color: #f0f0f0;
            border-top: 2px solid #000;
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }

        input, select, textarea {
            width: 100%;
            padding: 8px;
            border: 2px solid #000;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .text-danger {
            color: red;
            margin-top: 5px;
        }

        .alert {
            background-color: #ffcccb;
            padding: 10px;
            border: 2px solid #ff0000;
            margin-bottom: 15px;
            border-radius: 4px;
        }

        .alert ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .button-group {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
        }

        .btn-primary {
            background-color: #00008B;
            color: white;
            padding: 10px 20px;
            border-radius: 4px;
            border: 2px solid #000;
            font-size: 1rem;
            cursor: pointer;
        }

        .btn-primary:hover {
            background-color: darkblue;
        }

        .btn-secondary {
            color: #000;
            background-color: #d3d3d3;
            padding: 10px 20px;
            border-radius: 4px;
            text-decoration: none;
            border: 2px solid #000;
            font-size: 1rem;
        }

        .btn-secondary:hover {
            background-color: #b0b0b0;
        }
    </style>
</head>
<body>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">Update Your Profile</div>
        </div>
        <div class="window-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert">
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="text-danger">
                                {% for error in field.errors %}
                                    <small>{{ error }}</small>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="button-group">
                    <button type="submit" class="btn-primary">Update Profile</button>
                    <a href="{% url 'accounts:blank' %}" class="btn-secondary">Go Back to MAC</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>