dcan/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include, reverse
from django.conf.urls.static import static

from dcan import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: HttpResponseRedirect(reverse("accounts:blank"))),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('course/', include(('courses.urls', 'courses'), namespace='courses')),
    path('questionaire/', include(('qa.urls', 'qa'), namespace='qa')),
    path('backrooms/', include('chatroom.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qa/urls.py
from django.urls import path
from .views import *


urlpatterns = [

    path('question/create/', QuestionCreateView.as_view(), name='create_quest'),
    path('questions/', QuestionAllView.as_view(), name='all_questions'),
    path('myquestions/', MyQuestionAllView.as_view(), name='my_questions'),
    path('question/<int:question_id>/', QuestionDetailView.as_view(), name='detailed_question'),
    path('question/<int:question_id>/vote/', QuestionVoteView.as_view(), name='question_vote'),
    path('question/<int:question_id>/<int:comment_id>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path("question/<int:question_id>/delete/", QuestionDeleteView.as_view(), name="delete_question"),
    path('json_pull_request/', QuestionNamesViaJson.as_view(), name='json_pull_request'),
    path('question/<int:question_id>/question_status/', QuestionStatusTogglerView.as_view(), name='question_status'),
]

qa/models.py
# bu ne be: from tkinter.constants import CHORD
from PIL import Image
from django.contrib.contenttypes.models import ContentType
from django.db import models
from accounts.models import CustomUser


# Create your models here.
#vakit olursa modellerden imageI söküp yeni model yapacam

class Question(models.Model):
    STATUS = ((0, "OPEN"),
              (1, "CLOSED")
              )

    question = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='written_questions_by_student')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    tags = models.ManyToManyField("Tags", blank=True)
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)

    image = models.ImageField(upload_to='qa/', null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image)
            if img.height > 400 or img.width > 400:
                output_size = (400, 400)
                img.thumbnail(output_size)
                img.save(self.image.path)

    class Meta:
        ordering = ['-created_on']
    # Ordering is not a free operation. Each field you add to the ordering incurs a cost to your database.
    # Each foreign key you add will implicitly include all of its default orderings as well.
    # Order kullanma class metadan kurtulmak istiyoruz.

    def __str__(self):
        return f"{self.question} | {self.author}"


class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    answer = models.BooleanField(default=False)
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)

    image = models.ImageField(upload_to='comments/', null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image)
            if img.height > 400 or img.width > 400:
                output_size = (400, 400)
                img.thumbnail(output_size)
                img.save(self.image.path)

    def __str__(self):
        return f"Comment by {self.author}"


class Tags(models.Model):
    tag = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.tag


class Vote(models.Model):
    VOTE_CHOICES = (
        (0, 'none'),
        (1, 'up_votes'),
        (-1, 'down_votes'),
    )

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='votes', null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='votes', null=True, blank=True)
    vote = models.IntegerField(choices=VOTE_CHOICES, default=0)

    class Meta:
        unique_together = [('user', 'question'), ('user', 'comment')]

qa/forms.py
from django import forms

from chatroom.models import File
from .models import Question, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question', 'content', 'tags', 'image']
        widgets = {
            'question': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Sor!',
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Describe your question in detail',
            }),
            'tags': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control-file',
            }),
        }
        labels = {
            'question': 'Question Title',
            'content': 'Description',
            'tags': 'Tags (Optional)',
            'image': 'Attach Image (Opsiyonel)',
        }


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file']
        widgets = {
            'file': forms.FileInput(attrs={
                'class': 'form-control-file',

            })
        }

qa/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.core.paginator import Paginator
from .models import *
from .forms import *
from django.db.models import F
import json
# Create your views here.


from django.urls import reverse

# bunu arama fonksiyonun implemente edebilmek için eklemek zorunda kaldım no hate


class QuestionNamesViaJson(LoginRequiredMixin, View):
    def get(self, request):
        questions = Question.objects.all()
        questions_list = []

        for question in questions:
            # reverse ile url çekiyorum, js'te isme tıklandığında direkt sayfaya yönlendirsin diye
            question_url = reverse('qa:detailed_question', kwargs={'question_id': question.id})
            variable_name = question.author
            name = variable_name.username
            questions_list.append({"question": question.question,
                                   "id": question.id,
                                   "url": question_url,
                                   "author": name})
            # idyi belki bir işime yarar diye gönderiyorum (bence gerek olmayacak da)
        context = {"questions": questions_list}
        return JsonResponse(context)


class QuestionAllView(View):

    @staticmethod
    def get(request):
        # GOT EM ACCORDING TO VOTESTATION
        # AGGREGATE = 1 TIME ANNOTATE = QUERY SET
        questions = Question.objects.annotate(vote_score=F('up_votes') - F('down_votes')).order_by('status', '-vote_score')
        paginator = Paginator(questions, 5)
        page_number = request.GET.get('page')
        questions = paginator.get_page(page_number)

        return render(request, 'qa/all_questions.html', {'questions': questions})


class MyQuestionAllView(LoginRequiredMixin, View):

    @staticmethod
    def get(request):
        questions = Question.objects.annotate(vote_score=F('up_votes') - F('down_votes')).order_by('status','-vote_score')
        q = questions.filter(author=request.user)
        paginator = Paginator(q, 5)
        page_number = request.GET.get('page')

        q = paginator.get_page(page_number)

        return render(request, 'qa/myquestions.html', {'questions': q})


class QuestionDetailView(View):
    @staticmethod
    def get(request, question_id):

        question = get_object_or_404(Question, id=question_id)
        comments = Comment.objects.filter(question=question)
        return render(request, 'qa/detailed_question.html', {
            'question': question,
            'comments': comments,
        })

    def post(self, request, question_id):
        question = get_object_or_404(Question, id=question_id)

        content = request.POST.get('content', '').strip()
        image = request.FILES.get('image', None)
        if not content:
            return JsonResponse({'message': 'Content not provided'})

        comment = Comment(content=content, author=request.user, question=question)
        if image:
            comment.image = image
        comment.save()
        return JsonResponse({'message': 'Comment created',
                             'comment': {
                                 'author': request.user.first_name,
                                 'content': content,
                                 'image': comment.image.url if image else None,
                                 'id': comment.id,
                             }})


class QuestionCreateView(LoginRequiredMixin, View):
    login_url = 'accounts:login'
    template_name = 'qa/create_quest.html'

    def get(self, request):
        form = QuestionForm()
        return render(request, self.template_name, {'form': form})

    @staticmethod
    def post(request):

        if request.FILES:
            form = QuestionForm(request.POST, request.FILES)
        else:
            form = QuestionForm(request.POST)

        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            form.save_m2m()  # saves tags separately
            return redirect('qa:detailed_question', question_id=question.id)

        return render(request, 'qa/create_quest.html', {'form': form})


class QuestionDeleteView(LoginRequiredMixin, View):
    login_url = 'accounts:login'

    @staticmethod
    def post(request, question_id):
        try:
            question = get_object_or_404(Question, id=question_id, author=request.user)
            question.delete()
            return JsonResponse({'message': 'Question deleted'})
        except Question.DoesNotExist:
            return JsonResponse({'message': 'Question not found'}, status=404)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)


class QuestionStatusTogglerView(LoginRequiredMixin, View):
    login_url = 'accounts:login'

    def post(self, request, question_id):
        question = get_object_or_404(Question, id=question_id)
        if question.status == 0:
            question.status = 1
        else:
            question.status = 0
        context = {'status': question.status}
        if context:
            question.save()
            return JsonResponse(context)


class CommentDeleteView(LoginRequiredMixin, View):
    login_url = 'accounts:login'

    @staticmethod
    def post(request, question_id, comment_id):
        comment = get_object_or_404(Comment,
                                    question_id=question_id,
                                    id=comment_id,
                                    author=request.user)
        if request.user != comment.author:
            return HttpResponseForbidden('You are not authorized to delete this comment')
        else:
            try:
                if comment.image:
                    os.remove(comment.image.path)
                comment.delete()
                return JsonResponse({'message': 'Comment deleted'})
            except Comment.DoesNotExist:
                return JsonResponse({'message': 'Comment not found'}, status=404)
            except Exception as e:
                return JsonResponse({'error': str(e)}, status=500)


class QuestionVoteView(View):
    def post(self, request, question_id):
        try:
            question = get_object_or_404(Question, id=question_id)
            user = request.user

            if not user.is_authenticated:
                return JsonResponse({'error': 'User not authenticated'}, status=403)

            data = json.loads(request.body.decode('utf-8'))
            vote_type = data.get('vote_type')

            vote, created = Vote.objects.get_or_create(user=user, question=question)

            if vote_type == 'upvote':
                if vote.vote != 1:
                    question.up_votes += 1
                    if vote.vote == -1:
                        question.down_votes -= 1
                    vote.vote = 1
            elif vote_type == 'downvote':
                if vote.vote != -1:
                    question.down_votes += 1
                    if vote.vote == 1:
                        question.up_votes -= 1
                    vote.vote = -1

            vote.save()
            question.save()

            return JsonResponse({
                'up_votes': question.up_votes,
                'down_votes': question.down_votes
            })

        except Exception as e:
            print(f"Error: {str(e)}")
            return JsonResponse({'error': str(e)}, status=500)

qa/templates/qa/all_questions.html
{% extends 'qa/base_questions.html' %}
{% block extra_tabs %}
<a href="{% url 'qa:my_questions' %}">My Questions</a>
{% endblock %}
{% block title %}All Questions{% endblock %}

{% block title_bar_text %}All Questions{% endblock %}
{% block searchbar %}

{% endblock %}
{% block content %}
<ul class="list-group">
    {% for question in questions %}
    <li class="question-item">
        <a href="{% url 'qa:detailed_question' question.id %}">{{ question.question }}</a>
        <div class="question-meta">
            Asked by: {{ question.author }} | Status: {{ question.get_status_display }} |
            Votes: Up {{ question.up_votes }} | Down {{ question.down_votes }}
        </div>

        {% if question.tags.all %}
        <div class="tags">
            Tags:
            {% for tag in question.tags.all %}
            <span>{{ tag.tag }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </li>
    {% endfor %}
</ul>

<div class="pagination">
    {% if questions.has_previous %}
    <a href="?page={{ questions.previous_page_number }}">Previous</a>
    {% else %}
    <span>Previous</span>
    {% endif %}

    <span>Page {{ questions.number }} of {{ questions.paginator.num_pages }}</span>

    {% if questions.has_next %}
    <a href="?page={{ questions.next_page_number }}">Next</a>
    {% else %}
    <span>Next</span>
    {% endif %}
</div>
{% endblock %}

qa/templates/qa/base_questions.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Questions{% endblock %}</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />
    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            padding: 20px;
            margin: 0;
        }

        .tab-bar {
            background-color: #00008B;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .tab-bar a {
            color: #fff;
            text-decoration: none;
            font-weight: bold;
            padding: 10px 20px;
            background-color: #003580;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }

        .tab-bar a:hover {
            background-color: #000066;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 12px 16px;
            font-size: 1.5rem;
            text-align: center;
        }

        .window-body {
            padding: 20px;
        }

        .question-item {
            background-color: #f9f9f9;
            border: 1px solid #ccc;
            padding: 15px;
            margin-bottom: 15px;
            border-radius: 4px;
        }

        .question-item a {
            font-size: 1.2rem;
            font-weight: bold;
            text-decoration: none;
            color: #00008B;
        }

        .question-item a:hover {
            text-decoration: underline;
        }

        .question-meta {
            margin-top: 10px;
            font-size: 0.9rem;
            color: #666;
        }

        .tags {
            margin-top: 10px;
        }

        .tags span {
            display: inline-block;
            background-color: #00008B;
            color: #fff;
            padding: 5px 10px;
            margin-right: 5px;
            border-radius: 4px;
            font-size: 0.8rem;
        }

        .pagination {
            text-align: center;
            margin-top: 20px;
        }

        .pagination a {
            padding: 8px 16px;
            background-color: #00008B;
            color: #fff;
            border-radius: 4px;
            text-decoration: none;
            margin: 0 5px;
            transition: background-color 0.3s ease;
        }

        .pagination a:hover {
            background-color: #003580;
        }

        .pagination span {
            padding: 8px 16px;
            background-color: #ccc;
            color: #333;
            border-radius: 4px;
            margin: 0 5px;
        }

        #courseResults {
            display: none;
        }

        .search-bar .field {
        display: inline-block;
        background-color: #c0c0c0;
        border: 2px solid #000;
        padding: 2px;
        margin-bottom: 10px;
        }

        #courseSearchBar {
            border: none;
            width: 100%;
            padding: 3px;
        }

    .search-results {
        display: none;
        background-color: #f9f9f9;
        border: 2px solid #ccc;
        padding: 10px;
    }

    .search-result-item {
        padding: 5px;
        border-bottom: 1px solid #ddd;
        cursor: pointer;
    }

    .search-result-item:hover {
        background-color: #e0e0e0;
    }


    </style>
</head>
<body>
    <div class="tab-bar">
        <a href="{% url 'accounts:blank' %}">Back to MAC</a>
        <a href="{% url 'qa:create_quest' %}">New Question</a>
        {% block extra_tabs %}{% endblock %}
    </div>

    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">{% block title_bar_text %}All Questions{% endblock %}</div>
        </div>

        <div class="window-body">
            <div class="search-bar field">
                <input type="text" id="courseSearchBar"
                       placeholder="Search for question/author..."
                       onkeyup="handleSearch(event)"
                >
                <div class="search-results" id="searchResults"></div>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
<script src= "{% static 'qa/js/searcher.js' %}" > </script>
</body>
</html>

qa/templates/qa/create_quest.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a Question</title>
    <link rel="stylesheet" href="https://jdan.github.io/98.css/98.css" />

    <style>
        body {
            background-image: url("{% static 'accounts/starry.jpg' %}");
            padding: 20px;
            margin: 0;
        }

        .tab-bar {
            background-color: #00008B;
            padding: 10px;
            display: flex;
            justify-content: flex-start;
            margin-bottom: 20px;
        }

        .tab-bar a {
            color: #fff;
            text-decoration: none;
            font-weight: bold;
            padding: 10px 20px;
            background-color: #003580;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }

        .tab-bar a:hover {
            background-color: #000066;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .title-bar {
            background-color: #00008B;
            color: #fff;
            padding: 12px 16px;
            font-size: 1.5rem;
            text-align: center;
        }

        .window-body {
            padding: 20px;
        }

        h2 {
            font-size: 1.5rem;
            margin-bottom: 20px;
            color: #00008B;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        form input,
        form textarea,
        form select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 2px solid #00008B;
            border-radius: 4px;
            font-size: 1rem;
        }

        form button {
            background-color: #00008B;
            color: #fff;
            padding: 12px;
            border: none;
            border-radius: 4px;
            font-size: 1.1rem;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        form button:hover {
            background-color: #003580;
        }

        #id_tags {
            display: inline-block;
            width: 100%;
            height: auto;
            padding: 5px;
            font-size: 14px;
        }

    </style>
</head>
<body>
    <div class="tab-bar">
        <a href="{% url 'qa:all_questions' %}">Back to All Questions</a>
    </div>
    <div class="container window">
        <div class="title-bar">
            <div class="title-bar-text">Ask a Question</div>
        </div>
        <div class="window-body">
            <h2>Ask a Question</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_div }}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</body>
</html>

qa/templates/qa/myquestions.html
{% extends 'qa/base_questions.html' %}

{% block title %}My Questions{% endblock %}

{% block title_bar_text %}My Questions{% endblock %}

{% block extra_tabs %}
<a href="{% url 'qa:all_questions' %}">All Questions</a>
{% endblock %}

{% block content %}
<ul class="list-group">
    {% for question in questions %}
    <li class="question-item">
        <a href="{% url 'qa:detailed_question' question.id %}">{{ question.question }}</a>
        <div class="question-meta">
            Asked by: {{ question.author }} | Status: {{ question.get_status_display }} |
            Votes: Up {{ question.up_votes }} | Down {{ question.down_votes }}
        </div>

        {% if question.tags.all %}
        <div class="tags">
            Tags:
            {% for tag in question.tags.all %}
            <span>{{ tag.tag }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </li>
    {% endfor %}
</ul>

<div class="pagination">
    {% if questions.has_previous %}
    <a href="?page={{ questions.previous_page_number }}">Previous</a>
    {% else %}
    <span>Previous</span>
    {% endif %}

    <span>Page {{ questions.number }} of {{ questions.paginator.num_pages }}</span>

    {% if questions.has_next %}
    <a href="?page={{ questions.next_page_number }}">Next</a>
    {% else %}
    <span>Next</span>
    {% endif %}
</div>
{% endblock %}